### ISSUE TITLE
arrowIPCStream is broken

### ISSUE THREAD

**Issue by samansmink** [duckdblabs/arrow#4]
### What happens?

arrowIPCStream was working in 0.6.1 but is broken in 0.7.1.

It likely has to do with disabling the caching operators in https://github.com/duckdb/duckdb/pull/6435

### To Reproduce

```
import { db } from "./test/db.js";
import * as arrow from "apache-arrow";

function mergeBuffers(buffers) {
  const len = buffers.reduce((a, b) => a + b.length, 0);
  const buf = new Uint8Array(len);

  for (let i = 0, offset = 0; i < buffers.length; ++i) {
    buf.set(buffers[i], offset);
    offset += buffers[i].length;
  }

  return buf;
}

await db.csv("penguins", "../../data/penguins.csv");

// does not work
const stream = await db.con.arrowIPCStream("SELECT * FROM penguins");
const chunks = await stream.toArray();
console.log(chunks);
console.log(stream);
const table = arrow.tableFromIPC(mergeBuffers(chunks));
console.log(table.toArray());

// works and uses arrowIPCAll
// const ipcbuf = await db.arrowBuffer("SELECT * FROM penguins");
// console.log(mergeBuffers(chunks).length, ipcbuf.length);
// const table2 =  arrow.tableFromIPC(ipcbuf);
// console.log(table2.toArray())

```

### OS:

All probably

### DuckDB Version:

0.7.1

### DuckDB Client:

Node

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
@domoritz

**Comment by matt-allan** [comment]
I ran into this too. Here's a minimal reproduction that follows the structure of the test as much as possible: https://gist.github.com/matt-allan/39555313f6171658c49a53d13828848d

The arrow table doesn't have any rows. It works correctly with `arrowIPCAll`
